parameters:
#    nlemahieu_cms.example.class: nlemahieu\CmsBundle\Example

services:
#    nlemahieu_cms.example:
#        class: %nlemahieu_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
